# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f6579ea6fc0c7754d22e85845c07593762dce27d2cc0e1aaaa9e9e40f36e426195c5190345631428fe4df85b0af3f1aaca48572973d7c08b4b3d8b9433a290

test:
  secret_key_base: afa23164874ee1ea67f446827e05c33106da76461dc2177f43926807e4a453e6355d15546f22d9a407ed52677425ca1382bb9547d4c7100ecee1c413b356e66d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
